Add support for kubernetes endport field
cloudnativelabs/kube-router pull request #1080
Opened 2021-05-11 23:58 UTC by rikatz

This PR adds support for the recently added endPort field in kubernetes, which now is feature gated but will be marked as default in next release.

TODO:
* [ ] Improve tests
* [ ] Validate functioning with Kubernetes
* [ ] Verify need to change docs

2021-05-13 21:39 UTC, aauren commented
@rikatz Thanks for thinking of us and submitting this! Definitely appreciate it!

Give me a shout when you finish with the other checkboxes in there and want a review and I'll take another look.

I was looking at the documentation for this feature (https://kubernetes.io/docs/concepts/services-networking/network-policies/#targeting-a-range-of-ports) and I can't tell if this is only for egress, or if `endPort` can show up in both ingress and egress. Did only the `egress` specification change or both?

2021-05-13 22:03 UTC, rikatz commented
Hey @aauren for sure. I'm getting some time during this weekend to finish here.

EndPort works for both Ingress and Egress: It's part of the NetworkPolicyPort struct (used in both). In case of Ingress it's more feasible when working with Intra Pod communications (or headless) as services nowadays does not support portRanges (yet! there's a KEP ongoing about that).

https://github.com/kubernetes/enhancements/blob/master/keps/sig-network/2079-network-policy-port-range/README.md Here's the specification if you wanna take a look :)

Thank you very much!

2021-05-30 20:32 UTC, rikatz commented
@aauren I've added some unit tests, and tested the correct rule creation in Kubernetes as well. Everything seems to work fine, although I'm running inside KinD and it seems to be complaining about some things.

I'll try to run on a pure kubeadm cluster, but if you can take a look into the PR I would appreciate.

Thanks!!

2021-06-02 22:26 UTC, aauren requested changes
Overall it looks really good, thanks for implementing this for us!

I just and a question and two small changes requested.

2021-06-02 22:28 UTC, aauren commented
BTW I was also able to test this on my test cluster and validated that the rules were created as we expected.

2021-06-09 20:21 UTC, rikatz commented
Hey @aauren sorry for my long delay. I'll cycle back to this probably tomorrow :)

2021-06-13 19:35 UTC, rikatz commented on pkg/controllers/netpol/policy.go
> +					continue
Hum, agreed with you! Will change here. Actually the spec drops the netpol object in validation, when this situation happens so in this case this is a last resort here (we assume here that something wrong happened in k8s api validation).

2021-06-13 19:52 UTC, rikatz commented on pkg/controllers/netpol/network_policy_controller_test.go
> +		},
Added

2021-06-13 19:55 UTC, rikatz commented on pkg/controllers/netpol/policy.go
>  				if numericPort2eps, ok := protocol2eps[string(*npPort.Protocol)]; ok {
done :)

2021-06-13 19:58 UTC, rikatz commented
@aauren fixed per your comments and already squashed things (as those are minor changes!) 

Sorry once more about the delay, things are pretty busy here :)

2021-06-14 14:50 UTC, murali-reddy commented
thanks @rikatz for adding support for port ranges.

@aauren thanks for revewing. I had a chance to look at the PR. Changes LGTM.

2021-06-17 16:14 UTC, merged