[WIP] add logic to explicitly ACCEPT traffic from/to the pod
cloudnativelabs/kube-router pull request #1108
Opened 2021-06-21 21:33 UTC by murali-reddy

add logic in network policy controller to explicitly ACCEPT traffic from/to the pod in both cases

- ACCEPT traffic from the pod is permitted by applicable network policies. 
- ACCEPT traffic if there are no network policies appicable to the traffic

`0x20000` will be used to mark the traffic from/to the pod that matches above cases.

Rule is appened in kube-router's top level chain to  `ACCEPT` traffic if packet is marked `0x20000` 

Fixes https://github.com/cloudnativelabs/kube-router/issues/984

2021-06-22 13:47 UTC, murali-reddy commented
Fixes https://github.com/cloudnativelabs/kube-router/issues/1076 as well

2021-06-24 22:05 UTC, aauren requested changes
Conceptually everything here seems fine, however, I think there is a bit of code rework here possible to improve efficiency of the code and potentially the data path as well. All of the changes would be pretty minor.

I haven't had the chance to run this in a cluster, let me know if you want me to give it a spin after the changes are made, otherwise after changes this seems good to me.

2021-06-24 22:05 UTC, aauren commented on pkg/controllers/netpol/network_policy_controller.go
> +		err = iptablesCmdHandler.AppendUnique("filter", chain, args...)
I take it that the fact that we only accept our own traffic (i.e. traffic to/from pods) and don't comment on other traffic is purposeful right? i.e. the user can make their own firewall policy decisions for traffic that is not k8s based?

2021-06-25 21:42 UTC, murali-reddy commented on pkg/controllers/netpol/network_policy_controller.go
> +		klog.Fatalf("Failed to initialize iptables executor due to %s", err.Error())
Its fatal condition so program will exit

2021-06-25 21:42 UTC, murali-reddy commented on pkg/controllers/netpol/pod.go
> +	npc.filterTableRules.WriteString(strings.Join(args, " "))
Agree. Fixed now.

2021-06-25 21:43 UTC, murali-reddy commented on pkg/controllers/netpol/pod.go
> +	npc.filterTableRules.WriteString(strings.Join(args, " "))
Done

2021-06-25 21:43 UTC, murali-reddy commented on pkg/controllers/netpol/pod.go
> +	if !npc.isEgressNetworkPolicyEnabledPod(networkPoliciesInfo, pod) {
done

2021-06-25 21:43 UTC, murali-reddy commented on pkg/controllers/netpol/pod.go
> +func (npc *NetworkPolicyController) setupPodIngressRules(pod *podInfo, podFwChainName string, networkPoliciesInfo []networkPolicyInfo, version string) error {
Done

2021-06-25 21:44 UTC, murali-reddy commented
@aauren thanks for your review. I have incorporated requested changes.

2021-06-25 21:58 UTC, aauren approved these changes
Thanks @murali-reddy. Not sure if I'll get a chance to run it on one of our clusters, if I do I'll report back my results. Don't wait for me if you're satisfied with the results.

2021-06-25 22:01 UTC, aauren commented on pkg/controllers/netpol/network_policy_controller.go
> +		comment := "rule to explictly ACCEPT traffic that comply to network policies"
Linting check is failing because `explictly` here should be: `explicitly`

2021-06-25 22:01 UTC, aauren commented on pkg/controllers/netpol/pod.go
> +		// Mark will be checked to explictly ACCEPT the traffic
Same with `explicitly`

2021-06-28 17:45 UTC, merged