prometheus metrics: add option to specify listen address
cloudnativelabs/kube-router pull request #1244
Opened 2022-02-04 16:36 UTC by jpiper

In the situation that you have multiple interfaces/IP addresses, we want to be able to specify which one we want to expose the prometheus metrics on.

2022-02-08 04:00 UTC, aauren requested changes
Thanks for submitting. This seems reasonable. There is one piece of feedback that needs implementing, and it would also be helpful if you could squash your commits as these are all related to the same functionality and should be one atomic commit.

2022-02-19 18:53 UTC, jpiper commented
Yes! Sorry I haven’t had the chance to reply, I should be able to look at your comments this week

Sent from my iPhone

> On 19 Feb 2022, at 05:05, aauren ***@***.***> wrote:
> 
> ﻿
> @jpiper are you still interested in fixing up this PR so that we can merge it?
> 
> —
> Reply to this email directly, view it on GitHub, or unsubscribe.
> Triage notifications on the go with GitHub Mobile for iOS or Android. 
> You are receiving this because you were mentioned.

2022-03-18 21:25 UTC, aauren commented
@jpiper Just checking in again, are you still interested in this PR?

2022-05-29 20:14 UTC, aauren commented
Closing due to lack of updates

2022-05-29 20:14 UTC, closed without merging