fix: avoid to use http.DefaultServeMux which includes defaults routes inited by go like /debug/pprof
cloudnativelabs/kube-router pull request #1771
Opened 2024-11-26 04:13 UTC by morlay

https://cs.opensource.google/go/go/+/refs/tags/go1.23.3:src/net/http/pprof/pprof.go;l=100

metrics may just metrics

if enable pprof in metrics server, the flags `--enable-pprof` may be confused.

2024-11-28 19:42 UTC, aauren requested changes
Can you also do the same for the health controller as well? https://github.com/cloudnativelabs/kube-router/blob/master/pkg/healthcheck/health_controller.go#L223-L226

2024-11-28 19:42 UTC, aauren commented on pkg/metrics/metrics_controller.go
> +	mux := &http.ServeMux{}
Small nit here, can you change this to `http.NewServeMux()` instead? It amounts to the same, but seems better to use the default function provided.

2024-11-29 05:33 UTC, morlay commented
updated.

2024-11-30 19:13 UTC, aauren approved these changes
LGTM

Thanks for the contribution! :slightly_smiling_face:

2024-11-30 19:13 UTC, merged