fix(NSC): only set rp_filter to 2 if it is 1
cloudnativelabs/kube-router pull request #1791
Opened 2024-12-30 20:00 UTC by dsseng

Setting rp_filter to 2 when it is 0 will override its status to be always enabled (in the loose mode).
This behavior could break some networking solutions as it made packet admission rules more strict.

2024-12-30 20:01 UTC, dsseng commented
Also this doesn't work in all cases as I see, since this won't disable rp_filter on these in case all is set to 1 or 2:
https://github.com/cloudnativelabs/kube-router/blob/93498fb1acddbecc06fd404e5222071530e69bc3/pkg/controllers/proxy/linux_networking.go#L769-L787

2024-12-30 20:03 UTC, dsseng commented on pkg/controllers/proxy/network_services_controller.go
> +	for _, ifname := range []string{"all", "kube-bridge", nsc.krNode.GetNodeInterfaceName()} {
Is this list sufficient and specific to what we should check? I am not competent in kube-router's internal operation, so I do not know on which interfaces rp_filter could disrupt kube-router's operation.

2025-01-03 18:24 UTC, aauren requested changes
There's one linting error that needs correcting, and I left a request to add one more interface that I missed in our previous conversation, and I had one question.

I also deployed it to my test harness and while I haven't tested all of the boundary conditions for rp_filter values, I was able to confirm that it runs similar to how it ran before.

But other than that, this change looks really good! Thanks for putting this together for us!

2025-01-03 18:26 UTC, aauren commented
> Also this doesn't work in all cases as I see, since this won't disable rp_filter on these in case all is set to 1 or 2:
> 
> https://github.com/cloudnativelabs/kube-router/blob/93498fb1acddbecc06fd404e5222071530e69bc3/pkg/controllers/proxy/linux_networking.go#L769-L787

I'm not totally sure if I understand this comment correctly, doesn't the last case set rp_filter to `0` on the `all` interface and `0` is more permissive than `1` or `2`?

Also, just to be clear, this logic is setting that value for the interfaces found inside the container's network namespace in case that helps clarify anything for you.

2025-01-03 19:49 UTC, dsseng commented on pkg/controllers/proxy/network_services_controller.go
> +	if nsc.krNode.IsIPv4Capable() && rpFilter {
I agree we should perhaps override only the necessary interfaces (`"kube-bridge", "kube-dummy-if", nsc.krNode.GetNodeInterfaceName()`)

2025-01-03 19:50 UTC, dsseng commented
> > Also this doesn't work in all cases as I see, since this won't disable rp_filter on these in case all is set to 1 or 2:
> > https://github.com/cloudnativelabs/kube-router/blob/93498fb1acddbecc06fd404e5222071530e69bc3/pkg/controllers/proxy/linux_networking.go#L769-L787
> 
> I'm not totally sure if I understand this comment correctly, doesn't the last case set rp_filter to `0` on the `all` interface and `0` is more permissive than `1` or `2`?
> 
> Also, just to be clear, this logic is setting that value for the interfaces found inside the container's network namespace in case that helps clarify anything for you.

Okay, if it's inside the container that's not to be considered. Thanks for clarifying

2025-01-05 16:56 UTC, aauren reviewed
Thanks for the update! 2 more comments, but I think we're just about at the end here.

2025-01-05 16:56 UTC, aauren commented on pkg/controllers/proxy/network_services_controller.go
> +func checkRpFilter1(ifname string) bool {
nitpic, but this would probably be better named `checkRPFilter1` since `RP` is an acronym for reverse path.

2025-01-05 16:56 UTC, aauren commented on pkg/controllers/proxy/network_services_controller.go
> +			if rpFilterAll || checkRpFilter1(ifname) {
Just setting the `rp_filter` setting on the main interfaces is most likely enough, but I've had enough experience with this project where making smaller changes breaks some sort of edge case for someone else. So since I'm likely to miss some edge case for someone else in my testing, I'd feel better if we could just add the `all` interface here to this list instead of the check above.

My thought is that without setting `rp_filter` on the `all` interface, we'll miss the `veth` devices that are created by the CNI dynamically. We'll also miss other people's interfaces tunnelling interfaces for things like wireguard if they have those or some such.

Thoughts?

2025-01-05 19:54 UTC, dsseng commented on pkg/controllers/proxy/network_services_controller.go
> +			if rpFilterAll || checkRpFilter1(ifname) {
veth might be the case, yes. So perhaps if all is 1 we set it to 2, if 0 we keep it

2025-01-05 20:53 UTC, aauren commented on pkg/controllers/proxy/network_services_controller.go
> +			if rpFilterAll || checkRpFilter1(ifname) {
Yeah, I agree.

2025-01-11 17:39 UTC, aauren commented on pkg/controllers/proxy/network_services_controller.go
> +			if rpFilterAll || checkRpFilter1(ifname) {
Just wanted to check in, did you want to make this change? Or would you prefer for me to push to your branch with the change?

2025-01-11 18:28 UTC, dsseng commented on pkg/controllers/proxy/network_services_controller.go
> +			if rpFilterAll || checkRpFilter1(ifname) {
Ah, will do in a moment. Got caught into other tasks briefly. Sorry for a delay

2025-01-11 20:37 UTC, aauren approved these changes
LGTM!

Thanks so much for your contribution @dsseng!

2025-01-11 20:37 UTC, merged