Improve the ipAddrAdd performance
cloudnativelabs/kube-router pull request #965
Opened 2020-08-06 09:25 UTC by iamakulov

This PR replaces the `Exec()` call inside `ipAddrAdd()` with `netlink.RouteReplace()`.

When calling `ipAddrAdd` in a loop (e.g., inside `setupClusterIPServices`), this gives a significant performance boost.

2020-08-06 09:39 UTC, iamakulov commented on pkg/controllers/proxy/network_services_controller.go
> -	// route is not replaced. For now do it with command.
I believe this comment by @murali-reddy doesn’t hold true anymore. (Happy to be proven wrong.)

What I did to verify that `netlink.RouteReplace` works as intended:

1. Exec into a `kube-router` pod and install go and git:

   ```
   apk add go git
   ```

2. Create a file called `test-netlink.go`:

	```go
   	package main

	import (
		"github.com/golang/glog"
		"github.com/vishvananda/netlink"
		"golang.org/x/sys/unix"
		"net"
	)

	func main() {
		err := netlink.RouteReplace(&netlink.Route{
			Dst:       &net.IPNet{IP: net.ParseIP("5.5.5.5"), Mask: net.IPv4Mask(255, 255, 255, 255)},
			LinkIndex: 1,
			Table:     unix.RT_TABLE_LOCAL,
			Protocol:  unix.RTPROT_KERNEL,
			Scope:     unix.RT_SCOPE_HOST,
			Type:      unix.RTN_LOCAL,
			Src:       net.ParseIP("127.0.0.1"),
		})
		if err != nil {
			glog.Errorf("Failed to replace route to service. Error: %v", err)
		}
	}
	```

3. Install dependencies and pin `netlink` to the version which `kube-router` uses:

   ```sh
   go get
   cd $(go env GOPATH)/src/github.com/vishvananda/netlink
   git checkout f504738125a57f35f87fc30fb69b8df75237ccde # Version from Gopkg.lock
   ```

4. Run `test-netlink.go` and verify that the route got added:

   ```
   cd -
   go run test-netlink.go
   ip route show table all | grep 5.5.5.5
   # Should print: local 5.5.5.5 dev lo table local proto kernel scope host src 127.0.0.1
   ```

5. Change the source IP address in `test-netlink.go`, re-run it, and verify that the route gets replaced correctly:

   ```sh
   sed -i 's/127.0.0.1/172.17.0.2/' test-netlink.go
   go run test-netlink.go
   ip route show table all | grep 5.5.5.5
   # Should print: local 5.5.5.5 dev lo table local proto kernel scope host src 172.17.0.2
   ```

Is this a correct way to verify that?

2020-08-06 09:42 UTC, iamakulov commented on pkg/controllers/proxy/network_services_controller.go
> +		Type:      unix.RTN_LOCAL,
These parameters come from running the original `ip route replace ...` command through strace:

```
strace ip route replace local 10.97.216.74 dev kube-dummy-if table local proto kernel scope host src 172.17.0.2
```

which prints the system call with needed constants:

```
sendmsg(3, {msg_name={sa_family=AF_NETLINK, nl_pid=0, nl_groups=00000000}, msg_namelen=12, msg_iov=[{iov_base={{len=52, type=RTM_NEWROUTE, flags=NLM_F_REQUEST|NLM_F_ACK|NLM_F_REPLACE|NLM_F_CREATE, seq=1596701111, pid=0}, {rtm_family=AF_INET, rtm_dst_len=32, rtm_src_len=0, rtm_tos=0, rtm_table=RT_TABLE_LOCAL, rtm_protocol=RTPROT_KERNEL, rtm_scope=RT_SCOPE_HOST, rtm_type=RTN_LOCAL, rtm_flags=0}, [{{nla_len=8, nla_type=RTA_DST}, inet_addr("10.97.216.74")}, {{nla_len=8, nla_type=RTA_PREFSRC}, inet_addr("172.17.0.2")}, {{nla_len=8, nla_type=RTA_OIF}, if_nametoindex("kube-dummy-if")}]}, iov_len=52}], msg_iovlen=1, msg_controllen=0, msg_flags=0}, 0) = 52
```

2020-08-07 10:51 UTC, murali-reddy commented
@iamakulov thanks for your PR

We ran into some issues with `netlink.RouteReplace` on some distros and specific kernel versions. Please see https://github.com/cloudnativelabs/kube-router/issues/370#issuecomment-379415278

Action done by netlink routereplace was done to address specirfic issue with using service proxy in case of nodes with multiple network interface. This is the problem https://github.com/kubernetes/kubeadm/issues/102#issuecomment-291532883 and recommended solution https://kubernetes.io/docs/setup/production-environment/tools/kubeadm/install-kubeadm/#check-network-adapters. That piece of code is trying to automate above requirement.

On hindsight adding a route by exec command or with netlink libray for each VIP just does not scale. Now that kube-router has `--service-cluster-ip-range` we should all together remove setting up route for each cluster IP and set one rule to use node IP as source when destination is from the `--service-cluster-ip-range`

Not sure you have motivation to work on the fix, but here is what i think would be better approach

- remove whole `ip route` logic from the `ipAddrAdd`
- if `--service-cluster-ip-range` specified setup an ip rule to use node ip as source when destination is in given range

Unfortunatley CIDR that is used for cluster Ip's can not inferred from the kubernetes API's to we will have to rely on user input through this parameter.

2020-08-14 21:52 UTC, iamakulov commented
@murali-reddy Just took a round on your suggestion! Did I get your idea right?

2020-08-18 12:01 UTC, murali-reddy commented
thanks @iamakulov PR looks good. Will give a quick test and will update the PR.

2020-09-12 16:07 UTC, iamakulov commented
(Rebased on master.)

2020-09-16 09:05 UTC, murali-reddy commented
@iamakulov Apolgies for the delay in review. We are trying to get 1.1 release out in next couple of days. Marking for 1.2 release which is focussed on performance enhancements.

2020-09-19 00:40 UTC, iamakulov commented
Tested this patch in production, and it doesn’t work as expected.

1\) For new nodes, `nsc.enforceRightServiceInterface` gets called when `kube-dummy-if` doesn’t exist yet – and fails.

2\) The change resurrects https://github.com/cloudnativelabs/kube-router/issues/376.

`netlink.AddrAdd` not only associates an address with an interface, but also adds a route to the routing table. And the route uses the same IP address in the `src` field:

```sh
$ ip addr add 10.10.10.10 dev kube-dummy-if
$ ip addr list kube-dummy-if
8: kube-dummy-if: <BROADCAST,NOARP,UP,LOWER_UP> mtu 1500 qdisc noqueue state UNKNOWN group default 
    link/ether 56:51:fe:11:e3:02 brd ff:ff:ff:ff:ff:ff
    inet 10.10.10.10/32 brd 10.10.10.10 scope link kube-dummy-if
       valid_lft forever preferred_lft forever
$ ip route show table all | grep 10.10.10.10
local 10.10.10.10 dev kube-dummy-if table local proto kernel scope host src 10.10.10.10 # ← here, `src 10.10.10.10` is the problem
broadcast 10.10.10.10 dev kube-dummy-if table local proto kernel scope link src 10.10.10.10
```

Before, we were fixing this by calling `ip route replace` for each service IP. That was costly, so this PR removed that call and started calling `ip route replace <service-ip-cidr> ...`. But that resurrected https://github.com/cloudnativelabs/kube-router/issues/376 – because the CIDR route is less specific than `netlink.AddrAdd`’s routes and doesn’t have any effect.

---

To fix both issues, I’m going to change the approach:
* I’ll bring `ip route replace` back to `nsc.ln.ipAddrAdd()`
* and I’ll make `setupClusterIPServices` call `nsc.ln.ipAddrAdd()` only once (with the full services CIDR) instead of X times (for each service’s IP)

I’ll test this change in our system and then cherry-pick it here.

2020-09-19 00:46 UTC, iamakulov commented
Also, re: UX/DX.

This PR makes the `service-cluster-ip-range` param much more important. Before, if you specified it incorrectly (or if the default `10.96.0.0/16` value was wrong), it only affected network policies (which aren’t that common, I guess). Now, an incorrect value can break the service connectivity completely. (I learned this the hard way.)

Kubernetes already knows the `service-cluster-ip-range` value. Could kube-router retrieve it automatically and use the actual value (instead of a hard-coded default) in its defaults? That’d make life quite easier for a lot of people who aren’t that experienced with networking/Kubernetes administration (like me).

2020-09-22 20:16 UTC, aauren commented
@iamakulov While it's true that Kubernetes does know the service-cluster-ip-range value, as far as I know, it doesn't expose that information anywhere that is obtainable with through the API. Although, it may just be that it's not in a common place and I haven't run across it yet?

2020-09-22 21:28 UTC, iamakulov commented
> While it's true that Kubernetes does know the service-cluster-ip-range value, as far as I know, it doesn't expose that information anywhere that is obtainable with through the API. Although, it may just be that it's not in a common place and I haven't run across it yet?

Right, it appears that it’s not implemented: https://github.com/kubernetes/kubernetes/issues/25533 https://github.com/kubernetes/kubernetes/issues/46508

Would it be a viable idea to make `--service-cluster-ip-range` a required argument then? (To ensure that people _have_ to configure it properly – and don’t accidentally skip it and break their cluster.) I’m not sure how actually common is the `10.96.0.0/16` default, but at least kops uses `100.64.0.0/13` instead.

(If yes, it might be a good idea to also document how to retrieve this value – from `kubectl cluster-info dump | grep service-cluster-ip-range`.)

2021-03-19 21:27 UTC, aauren approved these changes
Finally coming back around this one. The only thing that I can see is that we should do as you suggest and make `--service-cluster-ip-range` a required argument as well as update the documentation in this area.

Otherwise this looks good to me.

2021-03-19 21:39 UTC, aauren requested changes

2021-03-19 21:39 UTC, aauren commented on pkg/controllers/proxy/network_services_controller.go
> +	err = ln.ipAddrAdd(tunIf, vip)
@iamakulov You missed another one of these changes on line 1229: https://github.com/cloudnativelabs/kube-router/blob/master/pkg/controllers/proxy/network_services_controller.go#L1229

2021-03-21 21:04 UTC, iamakulov commented
Hey!

I’m afraid I left the project I was working for when I implemented this patch, so I won’t be able to contribute fixes for this PR. Sorry!

However, as I mentioned in https://github.com/cloudnativelabs/kube-router/pull/965#issuecomment-695139094, this patch actually doesn’t work as expected, so this PR can’t be merged as-is. In the project I was working for, we ended up taking the alternative approach:

> To fix both issues, I’m going to change the approach:
> 
> * I’ll bring `ip route replace` back to `nsc.ln.ipAddrAdd()`
> * and I’ll make `setupClusterIPServices` call `nsc.ln.ipAddrAdd()` only once (with the full services CIDR) instead of X times (for each service’s IP)
> 
> I’ll test this change in our system and then cherry-pick it here.

– and this one worked well. It’s been running in production for a few months with no observable issues.

Let me know if there’s anything else I can help with!

2022-02-19 05:19 UTC, aauren commented
Closing as this PR is incomplete and the author unfortunately had to move on. In NPC we've started taking the approach of using ipset save and ipset restore, and likely we'll work that same functionality into the NSC in the future as well if we wanted to approach this problem again.

2022-02-19 05:19 UTC, closed without merging